"""Whitelist of tables/views that SQL Directo can query in iDempiere."""

ALLOWED_TABLES = {
    # Views LVE oficiales
    "lve_empleadosactivos", "lve_empleadosinactivos", "lve_familygroupemployee",
    "lve_disponibilidadbancaria", "lve_disponibilidadbancariateso",
    "lve_disponibilidadbancariagerencia",
    "lve_saldosclientes", "lve_saldosproveedor", "lve_saldosproductor",
    "lve_invoice", "lve_invoiceinproa", "lve_invoiceaga",
    "lve_sales_book", "lve_sales_books",
    "lve_buy_book", "lve_buy_book_sumary",
    "lve_fact_acct", "lve_trialbalance",
    "lve_informepago", "lve_resumencobro",
    "lve_customer_statement", "lve_supplier_statement",
    "lve_analisisvencimientoinproa",
    "lve_analisisvencimientodetalladolar", "lve_analisisvencimientoinproadolar",
    "lve_compromisosbancarios",
    "lve_payment", "lve_payment_receipt",
    "lve_anticipoproductor", "lve_anticipoproveedor",
    "lve_guiasmovilizacion", "lve_guiagranelsindespacho", "lve_guiacaleta",
    "lve_facturasvsentregas",
    "lve_inventario_terminado", "lve_inventario_paddy", "lve_inventario_maiz",
    "lve_inventario_empaque", "lve_inventario_granos",
    "lve_inventario_repuesto", "lve_inventario_comercial",
    "lve_inventario_semilla", "lve_inventario_proceso", "lve_inventario_procmaiz",
    "lve_inventario_costo", "lve_inventario_maquinaria",
    "lve_existenciayubicacion", "lve_existenciaalmacenagroinproa",
    "lve_dotacionemp", "lve_prestsempleados", "lve_activos",
    # Tablas raw necesarias (sin view LVE equivalente)
    "c_invoice", "c_invoiceline", "c_bpartner", "c_bpartner_location",
    "c_payment", "c_order", "c_orderline",
    "c_doctype", "c_currency", "c_tax",
    "ad_user", "ad_org",
    "m_product", "m_product_category", "m_inout", "m_inoutline",
    "m_production", "m_productionline", "m_storageonhand",
    "m_movement", "m_movementline",
    "pp_product_bom", "pp_product_bomline",
    "m_warehouse", "m_locator",
    "hr_employee", "hr_department", "hr_job", "hr_process", "hr_movement",
    "hr_concept", "hr_concept_category", "hr_payroll", "hr_contract",
    "hr_period", "hr_year", "hr_attribute",
    # Nota: hr_rule NO existe en Santoni. Tampoco hr_payslip.
    "fact_acct", "c_elementvalue",
    "c_bankaccount", "c_bank",
    "c_salesregion", "c_project",
    "c_location", "c_region", "c_country", "c_city",
    "c_bp_group",
    "c_allocationline", "c_allocationhdr",
    "c_paymentterm",
}
