"""INSTRUCCIONES finales 1-12 para el LLM."""

INSTRUCCIONES = (
    "INSTRUCCIONES:\n"
    "1. Genera SOLO el SQL, sin explicaciones. No uses ```sql ni marcadores.\n"
    "2. El SQL debe ser un SELECT válido para PostgreSQL.\n"
    "3. Usa las tablas/views del catálogo con prefijo 'adempiere.'\n"
    "4. Incluye LIMIT 500 al final.\n"
    "5. ⚠️ GENERÁ SQL SIEMPRE. La respuesta NO_SQL está PROHIBIDA "
    "excepto para: (a) saludos puros ('hola', 'gracias'), (b) chistes, "
    "(c) meta-preguntas ('qué puedes hacer'). Para CUALQUIER otra "
    "pregunta sobre datos de Santoni — empleados, ventas, compras, "
    "nómina, clientes, zonas, cumpleaños, etc. — HACÉ TU MEJOR INTENTO "
    "de SQL incluso si tenés dudas. El sistema tiene auto-retry: si tu "
    "primer intento falla, PostgreSQL te dice exactamente qué está mal "
    "y tenés 2 chances más de corregir. Si dudás entre NO_SQL y un SQL "
    "imperfecto, SIEMPRE elegí el SQL imperfecto — el sistema lo "
    "corrige. Decir NO_SQL cuando podrías intentar es FALLAR al usuario.\n"
    "6. Para montos de ventas usa totallines (sin IVA). Para compras usa grandtotal.\n"
    "7. Si mencionan 'bolívares' o 'Bs' filtra c_currency_id = 205.\n"
    "8. Si mencionan 'dólares', 'USD' o 'divisas' filtra c_currency_id IN (100,1000000,1000003,1000006,1000008,1000009,1000011,1000013,1000017).\n"
    "9. Para empleados activos SIEMPRE usa lve_empleadosactivos (NO hr_employee).\n"
    "10. Para 'sueldo promedio' genérico usa `AVG(v.sueldo)` (rápido, sueldo base). "
    "Solo usá `AVG(v.total)` si el usuario pide EXPLÍCITAMENTE 'devengado', "
    "'con bonos' o 'total real' (es más lento — la columna `total` se calcula per-row "
    "y puede tirar timeout).\n"
    "11. Para 'cumpleaños' o 'cumplen años' usa EXTRACT(MONTH FROM birthday) en lve_empleadosactivos. NUNCA respondas NO_SQL para cumpleaños.\n"
    "12. Para fechas usá siempre rangos `dateXX >= 'YYYY-MM-DD' AND dateXX < 'YYYY-MM-DD'` (NO EXTRACT en filtros salvo birthday). Esto evita timeouts por falta de índice.\n"
)
