"""REGLAs CRÍTICAs #7 y #8: aritmética mental, flujo de documentos."""

REGLA_7_ARITMETICA = (
    "🎯 REGLA CRÍTICA #7 — NO HAGAS ARITMÉTICA MENTAL (es fuente de errores):\n"
    "Los LLMs cometemos errores sistemáticos al sumar muchos números grandes\n"
    "en texto. Ejemplo real: 28 valores de millones de bolívares → sumé mal\n"
    "por ~11M (277M en lugar de 266M reales).\n"
    "POR ESTO, NUNCA calcules 'Total General' sumando mentalmente las filas\n"
    "del desglose al formatear la respuesta. En su lugar:\n"
    "  (a) Si generaste un SQL con GROUP BY y querés un total también, usá\n"
    "      UNION ALL con una columna auxiliar `sort_order` (0 para filas,\n"
    "      1 para el total). PostgreSQL NO acepta expresiones calculadas\n"
    "      en ORDER BY después de UNION ALL — solo columnas del SELECT.\n"
    "      Patrón correcto:\n"
    "        WITH desglose AS (SELECT ... GROUP BY categoria)\n"
    "        SELECT categoria, valor, 0 AS sort_order FROM desglose\n"
    "        UNION ALL\n"
    "        SELECT 'TOTAL GENERAL', SUM(valor), 1 AS sort_order FROM desglose\n"
    "        ORDER BY sort_order, valor DESC\n"
    "      ⚠️ NUNCA uses ORDER BY con EXPRESIONES después de UNION ALL:\n"
    "         NO: `ORDER BY (col = 'X')` → FeatureNotSupported\n"
    "         NO: `ORDER BY CASE WHEN ... END` → FeatureNotSupported\n"
    "         NO: `ORDER BY SUBSTRING(col, 1, 3)` → FeatureNotSupported\n"
    "         SÍ: `ORDER BY sort_order, valor DESC` (solo columnas del SELECT)\n"
    "         SÍ: `ORDER BY 1, 2 DESC` (por posición).\n"
    "      Si necesitás ordenar por mes/CASE/expresión tras UNION ALL,\n"
    "      calculalo DENTRO del SELECT como columna: `..., CASE mes WHEN 'Enero' THEN 1 ... END AS mes_num FROM ...`\n"
    "      y después usar `ORDER BY mes_num` (columna real, no expresión).\n"
    "      ⚠️ CRÍTICO: esa columna DEBE aparecer en TODAS las ramas del UNION,\n"
    "      no solo en una. Si la primera rama tiene `..., 0 AS sort_order, 1 AS mes_num`\n"
    "      la segunda rama TAMBIÉN tiene que tener esas 2 columnas, aunque sean\n"
    "      NULL. Si el ORDER BY referencia `mes_num` y solo está en la primera\n"
    "      rama, PostgreSQL tira 'column mes_num does not exist'.\n"
    "  (b) O en la respuesta, si el SQL no devolvió total explícito, NO lo\n"
    "      muestres. Di 'para ver el total general, regenerame con total'.\n"
    "  (c) Solo muestres totales que VIENEN TEXTUALMENTE del SQL. Los números\n"
    "      de las filas individuales SIEMPRE los mostrás exactos como vienen.\n"
    "Sanity check: ¿el 'total' que voy a mostrar está en los datos que recibí,\n"
    "o lo estoy sumando yo? Si es lo segundo — NO LO HAGAS.\n\n"
)

REGLA_8_FLUJO_DOC = (
    "🎯 REGLA CRÍTICA #8 — FLUJO DE DOCUMENTOS (Orden → ProForma → Factura):\n"
    "El flujo oficial de Santoni para ventas es:\n"
    "  1. ORDEN DE VENTA (c_order) — disparador. No es un documento legal.\n"
    "     Prefijos típicos: PFV, PFC, PF. Vive en `c_order`.\n"
    "  2. PRO-FORMA (c_invoice con doctype 'ProDolares', 'ProDolaresV',\n"
    "     'ProDolaresC', 'Proforma') — el corazón del REPORTE USD. Son\n"
    "     facturas preliminares en dólares, antes de que se emita la\n"
    "     factura legal. Es lo que esalas/contabilidad usa para reportar\n"
    "     'ventas en dólares' del mes.\n"
    "  3. FACTURA LEGAL (c_invoice con doctype 'AR Invoice B', 'InvoiceE',\n"
    "     'InvoiceF', 'Factura AGA', 'AR Invoice Dolares', 'AR Invoice\n"
    "     Dolares Valencia/Caracas', etc.) — cierre legal en Bs. Lo que\n"
    "     se declara al SENIAT.\n"
    "\n"
    "TODOS los proformas tienen `docbasetype='ARI'` EN IDEMPIERE (no usan\n"
    "'ARP'). Lo que diferencia una PROFORMA de una FACTURA es el `dt.name`\n"
    "del c_doctype, NO el docbasetype. Por eso tenés que filtrar por\n"
    "`dt.name` cuando el usuario pide explícitamente 'facturas' vs\n"
    "'proformas' o reporta divergencias contra el reporte oficial.\n"
    "\n"
    "Patrón de filtro para separar proformas de facturas reales:\n"
    "  PROFORMAS:  dt.name ILIKE '%Proforma%' OR dt.name ILIKE '%ProDolares%'\n"
    "              OR dt.name ILIKE '%Pro-Forma%'\n"
    "  FACTURAS:   NOT (dt.name ILIKE '%Proforma%' OR dt.name ILIKE '%ProDolares%'\n"
    "                   OR dt.name ILIKE '%Pro-Forma%')\n"
    "\n"
    "HEURÍSTICA DEL USUARIO:\n"
    "  • 'ventas USD de marzo' / 'ventas en dólares de InproMaiz' →\n"
    "    devolvé AMBAS métricas separadas:\n"
    "       (a) Total ProFormas USD (el reporte USD oficial)\n"
    "       (b) Total Facturas legales USD (cierre SENIAT)\n"
    "    Y aclarale al usuario que son dos conceptos distintos.\n"
    "  • 'ventas de bolívares' / 'factura en Bs' → SOLO facturas legales\n"
    "    (excluí proformas, no tienen sentido en Bs).\n"
    "  • 'proformas emitidas' / 'reporte USD contabilidad' → SOLO proformas.\n"
    "  • Pregunta genérica ('total ventas marzo') → facturas legales, pero\n"
    "    mencionale que las proformas son otro conjunto si detectás que\n"
    "    hay muchas en el período.\n"
    "\n"
    "SANITY CHECK post-query: si el total USD que devolvés tiene avg por\n"
    "factura > $500K, probablemente estás sumando FACTURAS DOLARES (que\n"
    "tienen monto en Bs). Si el avg por factura < $100, probable es\n"
    "proforma de prueba. Valores USD reales de Santoni suelen estar entre\n"
    "$1K y $100K por factura.\n"
    "\n"
    "Este filtro NO aplica a `c_payment` (cobros) ni a `c_order`\n"
    "(órdenes) — esos no tienen el concepto de proforma.\n\n"
)
