"""REGLA CRÍTICA #6 parte A: mapeo columna→tabla, org filter, ambigüedad name."""

REGLA_6_PARTE_A = (
    "🎯 REGLA CRÍTICA #6 — MAPEO COLUMNA → TABLA (Santoni específico):\n"
    "Guía rápida para evitar errores 'column does not exist':\n"
    "\n"
    "  Filtrar período en nómina → SIEMPRE `m.validfrom` (hr_movement).\n"
    "    No usar: p.hrdate, m.dateacct, m.startdate (no existen).\n"
    "    dateacct SOLO existe en hr_process; startdate SOLO en hr_period/hr_employee.\n"
    "\n"
    "  Nombre empleado en nómina → c_bpartner.name (hr_employee no tiene name).\n"
    "    JOIN c_bpartner bp ON m.c_bpartner_id = bp.c_bpartner_id.\n"
    "    Cédula: bp.taxid.\n"
    "\n"
    "  Región/zona de cliente → c_bpartner NO tiene c_region_id ni\n"
    "    c_salesregion_id directos. Hay que ir a través de c_bpartner_location:\n"
    "      JOIN c_bpartner_location bpl ON bp.c_bpartner_id = bpl.c_bpartner_id\n"
    "    Luego, para región geográfica: bpl.c_location_id → c_location.c_region_id\n"
    "    Para zona de venta: bpl.c_salesregion_id → c_salesregion (es la Zona\n"
    "    comercial tipo 'ZONA BARQUISIMETO', 'ZONA MARACAIBO').\n"
    "    NO uses ni `bp.c_salesregion_id` ni `loc.c_salesregion_id` —\n"
    "    la columna vive en `c_bpartner_location`.\n"
    "\n"
    "  Tablas que NO existen en Santoni: hr_payslip, hr_rule, hr_payroll_employee.\n"
    "  Usar hr_movement para cualquier consulta de nómina/pagos/ausentismo.\n\n"
    "  ⚠️ FILTRO DE ORG: usar SIEMPRE `ad_org_id IN (SELECT ...)`, NUNCA\n"
    "  `ad_org_id = (SELECT ...)`. Razón: ILIKE puede matchear múltiples\n"
    "  orgs (ej. 'AGROINPROA' matchea 'AGROINPROA C.A.' y otra variante),\n"
    "  y `= (subquery)` tira CardinalityViolation si la subquery devuelve\n"
    "  más de una fila. Con `IN (subquery)` funciona correctamente\n"
    "  matcheando TODAS las orgs.\n"
    "  NO: `WHERE ad_org_id = (SELECT ad_org_id FROM ad_org WHERE name ILIKE '%AGROINPROA%')`\n"
    "  SÍ: `WHERE ad_org_id IN (SELECT ad_org_id FROM ad_org WHERE name ILIKE '%AGROINPROA%')`\n"
    "  Esto aplica a TODAS las queries con filtro de org por ILIKE.\n"
    "\n"
    "  ⚠️ COLUMNA `name` AMBIGUA en lve_empleadosactivos + ad_org:\n"
    "  AMBAS tablas tienen columna `name` — la de lve_empleadosactivos\n"
    "  es el nombre del empleado, la de ad_org es el nombre de la org.\n"
    "  Cuando unís ambas (`JOIN ad_org o ON v.ad_org_id = o.ad_org_id`)\n"
    "  TODA columna del SELECT, WHERE y ORDER BY debe llevar alias:\n"
    "    NO: `SELECT name, cargo FROM lve_empleadosactivos JOIN ad_org ...`\n"
    "    SÍ: `SELECT v.name, v.cargo FROM lve_empleadosactivos v JOIN ad_org o ...`\n"
    "  La regla aplica para CUALQUIER JOIN donde las 2 tablas compartan\n"
    "  columnas (name, ad_org_id, isactive, created, etc.).\n"
    "\n"
    "  ⚠️ PERFORMANCE en lve_empleadosactivos con AGREGADOS (AVG/SUM/COUNT):\n"
    "  La view es pesada para agregados con subquery IN. Preferí JOIN\n"
    "  con ad_org que permite a PostgreSQL pushear el filtro de org:\n"
    "    LENTO (timeout): `FROM lve_empleadosactivos WHERE ad_org_id IN (SELECT ...)`\n"
    "    RÁPIDO: `FROM lve_empleadosactivos v JOIN ad_org o ON ... WHERE o.name ILIKE ...`\n"
    "  El JOIN también evita el problema de CardinalityViolation.\n"
    "\n"
)
