"""REGLA CRÍTICA #6 parte B: sintaxis PostgreSQL, columnas c_invoice, correlación."""

REGLA_6_PARTE_B = (
    "  ⚠️ SINTAXIS SQL — SOLO PostgreSQL (NUNCA Snowflake/BigQuery/MSSQL):\n"
    "    NO: `QUALIFY ranking <= 20` (es Snowflake/BigQuery, PostgreSQL NO lo tiene)\n"
    "    SÍ: `SELECT ... FROM (SELECT ..., ROW_NUMBER() OVER (...) AS rnk FROM ...) t\n"
    "         WHERE rnk <= 20`\n"
    "    NO: `TOP 10` (MSSQL) → usar `LIMIT 10`.\n"
    "    NO: `DATEADD(day, 30, date)` (MSSQL) → usar `date + 30` o `date + INTERVAL '30 days'`.\n"
    "    NO: `IIF(cond, a, b)` → usar `CASE WHEN cond THEN a ELSE b END`.\n"
    "  Si usás window functions (ROW_NUMBER, RANK, LAG), filtralas en\n"
    "  una subquery o CTE, NUNCA en QUALIFY.\n"
    "\n"
    "  ⚠️ COLUMNAS INEXISTENTES en c_invoice (errores recurrentes):\n"
    "    NO: `i.duedate` — no existe. Calcular: `i.dateinvoiced + COALESCE(pt.netdays, 30)`.\n"
    "    NO: `i.netdays` — no existe. `netdays` vive en `c_paymentterm` (JOIN).\n"
    "    NO: `ps.ispaid` inventando alias `ps` (no hay tabla schedule) →\n"
    "        usar directamente `i.ispaid` (columna real en c_invoice).\n"
    "    NO: `al.amount` si `al` alias de c_allocationhdr → amount vive\n"
    "        en c_allocationline, no en hdr. Alias correctos:\n"
    "        `c_allocationline al` (tiene amount, discountamt, writeoffamt).\n"
    "        `c_allocationhdr ah` (tiene dateacct, docstatus, NO tiene amount).\n"
    "    NO: `a.allocatedamt` — no existe en allocation. Usar SUM(al.amount)\n"
    "        agregado desde c_allocationline.\n"
    "  Para queries de CxC/saldos/vencimiento, ver el ejemplo\n"
    "  `Análisis de antigüedad de saldos` — usa SUBQUERY CORRELACIONADA\n"
    "  ESCALAR (la forma simple que SÍ puede referenciar `i`).\n"
    "\n"
    "  ⚠️ CORRELACIÓN: qué puede y qué NO puede ver el outer `i`:\n"
    "  \n"
    "  SÍ puede ver `i` → SCALAR SUBQUERY (aparece en SELECT o WHERE\n"
    "  como valor único, entre paréntesis):\n"
    "    (SELECT SUM(...) FROM c_allocationline al\n"
    "     WHERE al.c_invoice_id = i.c_invoice_id)  ✅ OK\n"
    "  \n"
    "  NO puede ver `i` → CTE (WITH ... AS) ni subquery en FROM/JOIN:\n"
    "    WITH alloc AS (... WHERE i.ad_org_id = X) ❌ ERROR\n"
    "    LEFT JOIN (SELECT ... WHERE i.ad_org_id = X) ❌ ERROR\n"
    "    → 'missing FROM-clause entry for table i'\n"
    "  \n"
    "  REGLA PRÁCTICA: si querés filtrar una agregación POR factura\n"
    "  específica (ej: saldo pagado de una factura), usá SCALAR SUBQUERY\n"
    "  correlacionada — es el patrón natural y funciona. Si querés\n"
    "  pre-agregar para TODAS las facturas de una vez, usá CTE sin\n"
    "  correlación (la CTE no puede filtrar por org específica; esa\n"
    "  filtrada la hacés en el outer).\n\n"
)
